"use client";
import Link from "next/link";
import { useState } from "react";

type Item={id:string;title:string;body?:string|null;description?:string|null;target_class?:string|null;created_at:string;file_name?:string|null};
const coach={name:"Mahendra Dhiwar",role:"STEM & Innovation Coach",bio:"Electronics engineer and STEM mentor helping students turn curiosity into real projects across electronics, AI, robotics and IoT.",tags:["STEM","Electronics","AI","Robotics","IoT"],achievements:["Google Certified Educator — Level 1","IBM Design Thinking Practitioner","ATL Sarthi EDC — 2","1st Position in 3rd Year B.Tech"],linkedin:"https://www.linkedin.com/in/mahendra-dhiwar-8a492515b/"};

export default function StudentDashboard({name,studentClass,section,announcements,resources}:{name:string;studentClass:string|null;section:string|null;announcements:Item[];resources:Item[]}){
 const firstName=name.split(" ")[0]; const [showCoach,setShowCoach]=useState(false);
 const visibleAnnouncements=announcements.filter(x=>!x.target_class||x.target_class===studentClass).slice(0,3);
 const visibleResources=resources.filter(x=>!x.target_class||x.target_class===studentClass).slice(0,4);
 const badges=[{icon:"⚡",name:"Curious Mind",on:true},{icon:"💡",name:"Idea Starter",on:!!studentClass},{icon:"🤖",name:"Robotics Explorer",on:false},{icon:"🏆",name:"Innovation Star",on:false}];
 return <main className="student-dashboard dashboard">
  <nav className="student-nav reveal"><Link href="/student" className="brand-lockup"><div><div className="brand">MINDVYORA</div><span className="pill">STUDENT</span></div></Link><div className="nav-actions"><span className="student-welcome">Hi, {firstName} 👋</span><Link className="button-secondary magnetic" href="/student/messages">💬 Chat</Link></div></nav>
  <section className="student-hero">
   <div className="hero-grid"/><div className="electric-lines"/><div className="spark-field"><i/><i/><i/><i/><i/><i/></div>
   <div className="hero-copy reveal delay-1"><p className="eyebrow">YOUR LEARNING SPACE · {studentClass?`CLASS ${studentClass}`:"ONLINE"}</p><h1>Welcome back,<br/><span>{firstName}.</span></h1><p className="muted hero-sub">Learn. Build. Innovate. Your next idea starts here.</p><div className="actions"><Link className="hero-button magnetic" href="/student/resources">Explore Resources <b>→</b></Link><Link className="secondary-button magnetic" href="/student/announcements">Announcements <b>↗</b></Link></div></div>
   <div className="hero-visual reveal delay-2" aria-hidden="true"><div className="visual-ring ring-a"/><div className="visual-ring ring-b"/><div className="visual-ring ring-c"/><div className="visual-core"><div className="core-glow"/><div className="core-book"><span>✦</span><span>⌁</span><span>◇</span></div></div><div className="float-icon icon-bulb">💡</div><div className="float-icon icon-robot">🤖</div><div className="float-icon icon-chip">▦</div><div className="float-icon icon-code">&lt;/&gt;</div><div className="float-icon icon-rocket">🚀</div></div>
  </section>

  <section className="section reveal delay-2"><div className="section-head"><div><p className="eyebrow">YOUR COMMAND CENTER</p><h2>Everything you need.</h2></div><span className="class-chip">CLASS {studentClass||"—"}{section?` · ${section}`:""}</span></div><div className="quick-grid">
   <Link className="quick purple lightning-card interactive" href="/student/resources"><span>📚</span><small>LEARNING HUB</small><h3>Resources</h3><p>{visibleResources.length} recent learning item{visibleResources.length===1?"":"s"} available.</p><b>Open →</b><em/></Link>
   <Link className="quick blue lightning-card interactive" href="/student/messages"><span>💬</span><small>DIRECT SUPPORT</small><h3>Coach Chat</h3><p>Ask a question or get help with your project.</p><b>Message →</b><em/></Link>
   <div className="quick green lightning-card interactive"><span>⚡</span><small>YOUR JOURNEY</small><h3>Progress</h3><div className="progress"><i/><strong>Getting started</strong></div><p>Complete activities to unlock achievements.</p><em/></div>
  </div></section>

  <section className="content-grid reveal delay-3"><div className="panel lightning-card"><div className="panel-head"><div><p className="eyebrow">LATEST</p><h3>Announcements</h3></div><Link href="/student/announcements">View all ↗</Link></div>{visibleAnnouncements.length?visibleAnnouncements.map((a,i)=><div className="feed stagger" style={{"--i":i} as React.CSSProperties} key={a.id}><span className="feed-icon">📢</span><div><strong>{a.title}</strong><p>{a.body||"New announcement from your coach."}</p><small>{a.target_class?`Class ${a.target_class}`:"All students"}</small></div></div>):<div className="empty">You're all caught up. New announcements will appear here.</div>}</div>
   <div className="panel lightning-card"><div className="panel-head"><div><p className="eyebrow">NEW MATERIAL</p><h3>Resources</h3></div><Link href="/student/resources">Browse all ↗</Link></div>{visibleResources.length?visibleResources.map((r,i)=><Link className="resource-row stagger" style={{"--i":i} as React.CSSProperties} href="/student/resources" key={r.id}><span className="file-icon">{r.file_name?.toLowerCase().endsWith(".pdf")?"PDF":"FILE"}</span><div><strong>{r.title}</strong><small>{r.target_class?`Class ${r.target_class}`:"All students"}</small></div><b>↓</b></Link>):<div className="empty">No resources yet. Check back soon.</div>}</div></section>

  <section className="achievement-section reveal delay-4"><div className="section-head"><div><p className="eyebrow">YOUR ACHIEVEMENTS</p><h2>Collect your wins.</h2></div><span className="badge-count">{badges.filter(b=>b.on).length}/{badges.length} unlocked</span></div><div className="badge-grid">{badges.map((b,i)=><div className={`badge ${b.on?"unlocked":"locked"} stagger`} style={{"--i":i} as React.CSSProperties} key={b.name}><span>{b.icon}</span><div><strong>{b.name}</strong><small>{b.on?"Unlocked":"Keep learning to unlock"}</small></div></div>)}</div></section>

  <section className="coach-trigger lightning-card reveal delay-4 interactive" onClick={()=>setShowCoach(true)} role="button" tabIndex={0} onKeyDown={e=>{if(e.key==="Enter"||e.key===" ")setShowCoach(true)}}><div className="coach-mark">M</div><div><p className="eyebrow">KNOW YOUR COACH</p><h3>Meet Mahendra Dhiwar</h3><p>STEM • AI • Robotics</p></div><b>Explore profile →</b></section>

  {showCoach&&<div className="modal-backdrop" onClick={()=>setShowCoach(false)}><section className="coach-modal lightning-card" onClick={e=>e.stopPropagation()} role="dialog" aria-modal="true"><button className="close" onClick={()=>setShowCoach(false)}>×</button><div className="coach-head"><div className="coach-avatar">M</div><div><p className="eyebrow">YOUR COACH</p><h2>{coach.name}</h2><p>{coach.role}</p></div></div><p className="bio">{coach.bio}</p><div className="tags">{coach.tags.map(t=><span key={t}>{t}</span>)}</div><h4>Achievements</h4><div className="achievements">{coach.achievements.map(a=><div key={a}>✦ {a}</div>)}</div><div className="modal-actions"><Link className="hero-button" href="/student/messages">Chat with coach →</Link><a className="secondary-button" href={coach.linkedin} target="_blank" rel="noreferrer">LinkedIn ↗</a></div></section></div>}
  <footer>MINDVYORA © 2026 <span>•</span> Crafted with ❤️ by Mahendra Dhiwar <span>•</span> STEM • AI • Robotics</footer>

  <style jsx global>{`
.student-dashboard{max-width:1240px!important;padding-top:24px!important;overflow:hidden}.student-nav{display:flex;justify-content:space-between;align-items:center;margin-bottom:24px}.student-nav .brand-lockup{display:flex;align-items:center;gap:10px}.student-nav .brand{font-size:21px}.student-welcome{font-size:12px;color:#aaa5b4}.student-nav .button-secondary{padding:10px 14px;border-radius:999px}.reveal{animation:rise .75s cubic-bezier(.2,.8,.2,1) both}.delay-1{animation-delay:.08s}.delay-2{animation-delay:.16s}.delay-3{animation-delay:.24s}.delay-4{animation-delay:.32s}
.student-hero{position:relative;min-height:430px;padding:58px;border-radius:30px;overflow:hidden;border:1px solid #343050;background:radial-gradient(circle at 82% 40%,rgba(80,80,255,.16),transparent 24%),radial-gradient(circle at 88% 78%,rgba(185,60,255,.17),transparent 28%),linear-gradient(135deg,#060b19,#0b0b14 55%,#12091b);box-shadow:inset 0 0 70px rgba(124,58,237,.04),0 30px 100px rgba(0,0,0,.24)}.hero-grid{position:absolute;inset:0;opacity:.14;background-image:linear-gradient(rgba(167,139,250,.16) 1px,transparent 1px),linear-gradient(90deg,rgba(34,211,238,.12) 1px,transparent 1px);background-size:48px 48px;mask-image:linear-gradient(to right,transparent,black 35%,black 80%,transparent);animation:gridMove 18s linear infinite}.electric-lines{position:absolute;inset:-20%;opacity:.42;background:linear-gradient(165deg,transparent 18%,rgba(0,200,255,.85) 18.15%,transparent 18.4% 39%,rgba(139,92,246,.85) 39.15%,transparent 39.4% 67%,rgba(217,70,239,.8) 67.15%,transparent 67.4%);animation:flash 4.8s ease-in-out infinite;filter:blur(.2px)}.electric-lines:after{content:"";position:absolute;inset:0;background:linear-gradient(178deg,transparent 28%,rgba(34,211,238,.85) 28.12%,transparent 28.4% 54%,rgba(167,139,250,.85) 54.12%,transparent 54.4%);opacity:0;animation:flash 6.7s 1.7s infinite}.spark-field{position:absolute;inset:0;pointer-events:none}.spark-field i{position:absolute;width:3px;height:3px;border-radius:50%;background:#c4b5fd;box-shadow:0 0 14px #8b5cf6;animation:twinkle 2.5s ease-in-out infinite}.spark-field i:nth-child(1){left:64%;top:18%}.spark-field i:nth-child(2){left:76%;top:30%;animation-delay:.7s}.spark-field i:nth-child(3){left:90%;top:23%;animation-delay:1.2s}.spark-field i:nth-child(4){left:70%;top:78%;animation-delay:1.8s}.spark-field i:nth-child(5){left:84%;top:66%;animation-delay:.4s}.spark-field i:nth-child(6){left:94%;top:52%;animation-delay:2s}.hero-copy{position:relative;z-index:4;max-width:680px}.hero-copy h1{font-size:clamp(50px,6vw,78px);line-height:.92;letter-spacing:-.07em;margin:12px 0}.hero-copy h1 span{color:#a78bfa;text-shadow:0 0 35px rgba(167,139,250,.18)}.hero-sub{font-size:15px}.actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:28px}.secondary-button{display:inline-flex;align-items:center;gap:14px;padding:14px 17px;border:1px solid #4a3c5d;border-radius:14px;background:rgba(8,8,13,.5);color:#ded9e8;font-size:12px;font-weight:800;transition:.3s}.secondary-button:hover{transform:translateY(-3px) scale(1.02);border-color:#9a70d0;box-shadow:0 0 25px rgba(124,58,237,.2)}.magnetic{transition:transform .25s ease,box-shadow .25s ease}.magnetic:hover{transform:translateY(-3px) scale(1.02);box-shadow:0 15px 35px rgba(91,33,182,.18)}
.hero-visual{position:absolute;right:5%;top:50%;transform:translateY(-50%);width:420px;height:360px;z-index:2}.visual-ring{position:absolute;left:50%;top:50%;border:1px solid rgba(167,139,250,.2);border-radius:50%;transform:translate(-50%,-50%);animation:spin 14s linear infinite}.ring-a{width:340px;height:150px;transform:translate(-50%,-50%) rotate(-20deg)}.ring-b{width:370px;height:210px;transform:translate(-50%,-50%) rotate(35deg);animation-direction:reverse;animation-duration:19s}.ring-c{width:260px;height:300px;transform:translate(-50%,-50%) rotate(70deg);border-color:rgba(34,211,238,.15);animation-duration:11s}.visual-core{position:absolute;left:50%;top:50%;width:150px;height:150px;transform:translate(-50%,-50%);border-radius:36px;display:grid;place-items:center;background:radial-gradient(circle at 35% 25%,#fff,#b79cff 13%,#6d28d9 44%,#16102d 78%);box-shadow:0 0 100px rgba(124,58,237,.3),inset 0 0 30px rgba(255,255,255,.12);animation:corePulse 3.8s ease-in-out infinite}.core-glow{position:absolute;inset:-20px;border-radius:45px;background:radial-gradient(circle,rgba(124,58,237,.35),transparent 65%);animation:glowPulse 2.8s ease-in-out infinite}.core-book{position:relative;width:85px;height:60px;border:2px solid rgba(255,255,255,.8);border-radius:8px 8px 20px 20px;display:flex;align-items:center;justify-content:space-around;color:#fff;font-size:19px;box-shadow:0 0 20px rgba(255,255,255,.22);transform:perspective(180px) rotateX(18deg)}.core-book:after{content:"";position:absolute;left:50%;top:5px;bottom:5px;width:1px;background:rgba(255,255,255,.5)}.float-icon{position:absolute;width:48px;height:48px;display:grid;place-items:center;border:1px solid rgba(167,139,250,.35);border-radius:15px;background:rgba(10,8,18,.72);backdrop-filter:blur(10px);box-shadow:0 10px 30px rgba(0,0,0,.25),0 0 20px rgba(124,58,237,.12);font-size:20px;animation:floatIcon 4.5s ease-in-out infinite}.icon-bulb{left:17%;top:15%}.icon-robot{right:8%;top:18%;animation-delay:.8s}.icon-chip{left:9%;bottom:22%;animation-delay:1.4s;color:#67e8f9;font-size:24px}.icon-code{right:12%;bottom:20%;animation-delay:2s;color:#c4b5fd;font-weight:900}.icon-rocket{left:50%;top:3%;animation-delay:2.6s}
.section,.achievement-section{margin-top:52px}.section-head{display:flex;justify-content:space-between;align-items:flex-end;gap:20px;margin-bottom:18px}.section-head h2{margin:7px 0 0;font-size:34px;letter-spacing:-.05em}.class-chip,.badge-count{padding:8px 11px;border:1px solid #302b38;border-radius:999px;color:#898592;font-size:10px;animation:softGlow 3s ease-in-out infinite}.quick-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.quick{position:relative;min-height:180px;padding:24px;border:1px solid #302b3d;border-radius:24px;overflow:hidden;background:#111016;transition:.35s cubic-bezier(.2,.8,.2,1)}.quick:hover{transform:translateY(-7px);border-color:#72528e;box-shadow:0 25px 70px rgba(0,0,0,.28),0 0 30px rgba(124,58,237,.08)}.quick:before{content:"";position:absolute;inset:-2px;background:conic-gradient(from 0deg,transparent 0 72%,rgba(167,139,250,.8) 78%,transparent 84%);animation:borderRun 5s linear infinite;opacity:0}.quick:hover:before{opacity:1}.quick:after{content:"";position:absolute;inset:1px;border-radius:23px;background:inherit;z-index:0}.quick>*{position:relative;z-index:1}.quick>span{font-size:23px;display:inline-block;animation:iconBob 3s ease-in-out infinite}.quick small{display:block;margin-top:18px;color:#898592;font-size:9px;letter-spacing:.14em}.quick h3{margin:5px 0;font-size:23px}.quick p{margin:0;color:#777481;font-size:11px;line-height:1.5;max-width:280px}.quick>b{position:absolute!important;right:22px;bottom:22px;color:#bda8ed;font-size:11px}.purple{background:linear-gradient(145deg,rgba(76,29,149,.18),#111016)}.blue{background:linear-gradient(145deg,rgba(30,64,175,.18),#111016)}.green{background:linear-gradient(145deg,rgba(5,150,105,.12),#111016)}.progress{display:flex;align-items:center;gap:9px;margin:13px 0}.progress i{display:block;width:100px;height:6px;border-radius:99px;background:linear-gradient(90deg,#22d3ee 28%,#243238 28%);animation:progressShimmer 2.5s linear infinite}.progress strong{font-size:10px;color:#aaa5b4}
.content-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:14px}.panel{padding:24px;border:1px solid #302b3d;border-radius:24px;background:#101015;transition:.3s}.panel:hover{border-color:#4c3b5f;box-shadow:0 20px 55px rgba(0,0,0,.2)}.panel-head{display:flex;justify-content:space-between;align-items:flex-start;margin-bottom:10px}.panel-head h3{margin:5px 0;font-size:22px}.panel-head a{font-size:10px;color:#a78bfa;transition:.2s}.panel-head a:hover{transform:translateX(3px)}.feed,.resource-row{display:flex;gap:12px;padding:14px 0;border-top:1px solid #24212a}.feed-icon,.file-icon{flex:none;width:34px;height:34px;display:grid;place-items:center;border-radius:11px;background:#1b1724}.feed-icon{animation:iconBob 3.5s ease-in-out infinite}.feed strong,.resource-row strong{font-size:12px}.feed p{margin:4px 0;color:#777481;font-size:10px;line-height:1.45}.feed small,.resource-row small{color:#8f7db5;font-size:9px}.resource-row{align-items:center;color:inherit;transition:.25s}.resource-row:hover{padding-left:6px;background:linear-gradient(90deg,rgba(124,58,237,.05),transparent)}.file-icon{font-size:8px;color:#bda8ed;border:1px solid #392d4b}.resource-row div{flex:1}.resource-row b{color:#9f8bd1}.empty{padding:28px 0;color:#66616d;font-size:11px}
.badge-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.badge{display:flex;gap:12px;align-items:center;padding:17px;border-radius:19px;border:1px solid #302b3d;background:#101015;transition:.3s}.badge:hover{transform:translateY(-5px);border-color:#644b7c;box-shadow:0 16px 40px rgba(0,0,0,.22)}.badge>span{font-size:24px;animation:iconBob 3.4s ease-in-out infinite}.badge strong{display:block;font-size:11px}.badge small{display:block;margin-top:4px;color:#66616d;font-size:9px}.badge.locked{opacity:.42;filter:saturate(.3)}.coach-trigger{display:flex;align-items:center;gap:18px;margin-top:16px;padding:22px;border:1px solid #3b2d55;border-radius:24px;background:linear-gradient(110deg,rgba(124,58,237,.1),rgba(255,255,255,.02));cursor:pointer;transition:.35s}.coach-trigger:hover{transform:translateY(-6px);border-color:#7955a9;box-shadow:0 25px 65px rgba(0,0,0,.24),0 0 30px rgba(124,58,237,.08)}.coach-mark{width:62px;height:62px;display:grid;place-items:center;border-radius:18px;background:linear-gradient(145deg,#9f7aea,#4c1d95);font-size:24px;font-weight:900;animation:corePulse 4s ease-in-out infinite}.coach-trigger h3{margin:4px 0;font-size:21px}.coach-trigger p:last-child{margin:0;color:#817d89;font-size:11px}.coach-trigger>b{margin-left:auto;color:#c4b5fd;font-size:11px}.modal-backdrop{position:fixed;inset:0;z-index:100;display:grid;place-items:center;padding:20px;background:rgba(2,2,6,.78);backdrop-filter:blur(15px);animation:fadeIn .25s ease}.coach-modal{position:relative;width:min(680px,100%);max-height:90vh;overflow:auto;padding:30px;border:1px solid #51396f;border-radius:28px;background:#0e0c13;box-shadow:0 40px 120px rgba(0,0,0,.65);animation:modalIn .45s cubic-bezier(.2,.9,.2,1)}.close{position:absolute;right:18px;top:16px;width:34px;height:34px;border:1px solid #3c3347;border-radius:50%;background:#17131d;color:#fff;font-size:22px;cursor:pointer}.coach-head{display:flex;align-items:center;gap:15px}.coach-avatar{width:68px;height:68px;display:grid;place-items:center;border-radius:21px;background:linear-gradient(145deg,#a78bfa,#4c1d95);font-size:28px;font-weight:900;box-shadow:0 0 35px rgba(124,58,237,.2)}.coach-head h2{margin:3px 0}.coach-head p:last-child{margin:0;color:#8c8695;font-size:12px}.bio{color:#a6a1ad;line-height:1.6;font-size:12px}.tags{display:flex;flex-wrap:wrap;gap:7px}.tags span{padding:7px 9px;border:1px solid #382e45;border-radius:999px;color:#c4b5fd;font-size:9px}.coach-modal h4{margin:22px 0 10px}.achievements{display:grid;gap:8px;color:#b9b2c2;font-size:11px}.modal-actions{display:flex;gap:10px;margin-top:24px}footer{text-align:center;padding:42px 0 15px;color:#57515f;font-size:9px}footer span{margin:0 7px;color:#7d5ba3}
@keyframes rise{from{opacity:0;transform:translateY(18px)}to{opacity:1;transform:none}}@keyframes fadeIn{from{opacity:0}to{opacity:1}}@keyframes modalIn{from{opacity:0;transform:translateY(18px) scale(.97)}to{opacity:1;transform:none}}@keyframes flash{0%,70%,100%{opacity:.2;transform:translateX(0)}74%{opacity:.9;transform:translateX(3px)}76%{opacity:.15;transform:translateX(-2px)}78%{opacity:.75;transform:translateX(2px)}}@keyframes gridMove{to{background-position:48px 48px}}@keyframes twinkle{0%,100%{opacity:.2;transform:scale(.6)}50%{opacity:1;transform:scale(1.7)}}@keyframes spin{to{transform:translate(-50%,-50%) rotate(360deg)}}@keyframes float{0%,100%{transform:translateY(0)}50%{transform:translateY(-10px)}}@keyframes floatIcon{0%,100%{transform:translateY(0) rotate(-2deg)}50%{transform:translateY(-10px) rotate(3deg)}}@keyframes corePulse{0%,100%{box-shadow:0 0 55px rgba(124,58,237,.24),inset 0 0 30px rgba(255,255,255,.08)}50%{box-shadow:0 0 105px rgba(124,58,237,.42),0 0 35px rgba(34,211,238,.14),inset 0 0 35px rgba(255,255,255,.14)}}@keyframes glowPulse{0%,100%{opacity:.35;transform:scale(.9)}50%{opacity:.8;transform:scale(1.15)}}@keyframes borderRun{to{transform:rotate(360deg)}}@keyframes progressShimmer{0%{filter:brightness(.9)}50%{filter:brightness(1.5)}100%{filter:brightness(.9)}}@keyframes iconBob{0%,100%{transform:translateY(0)}50%{transform:translateY(-4px)}}@keyframes softGlow{0%,100%{box-shadow:0 0 0 rgba(124,58,237,0)}50%{box-shadow:0 0 22px rgba(124,58,237,.08)}}
@media(max-width:900px){.hero-visual{opacity:.35;right:-8%}.quick-grid{grid-template-columns:1fr}.badge-grid{grid-template-columns:repeat(2,1fr)}.content-grid{grid-template-columns:1fr}.student-hero{padding:44px 30px}}@media(max-width:600px){.student-dashboard{padding:18px 14px!important}.student-nav{margin-bottom:15px}.student-nav .brand{font-size:18px}.student-welcome{display:none}.student-hero{min-height:520px;padding:35px 24px}.hero-copy h1{font-size:52px}.hero-visual{width:330px;height:290px;right:-65px;top:68%;opacity:.6}.visual-core{width:115px;height:115px}.core-book{transform:scale(.8) perspective(180px) rotateX(18deg)}.ring-a{width:270px}.ring-b{width:300px}.ring-c{height:250px}.float-icon{width:40px;height:40px;font-size:16px}.section,.achievement-section{margin-top:38px}.section-head h2{font-size:28px}.class-chip{display:none}.quick{min-height:165px}.badge-grid{grid-template-columns:1fr}.coach-trigger{align-items:flex-start}.coach-trigger>b{display:none}.modal-actions{flex-direction:column}.modal-actions>*{justify-content:center}}@media(prefers-reduced-motion:reduce){*,*::before,*::after{animation-duration:.01ms!important;animation-iteration-count:1!important;scroll-behavior:auto!important;transition-duration:.01ms!important}}
`}</style>
 </main>;
}
