"use client";
import { FormEvent, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import type { Student } from "./page";

type StudentForm = { school_id: string; student_code: string; full_name: string; class_name: string; section: string; roll_number: string };
type Stats = { resourceCount: number; announcementCount: number; messageCount: number };
const emptyForm: StudentForm = { school_id: "", student_code: "", full_name: "", class_name: "", section: "", roll_number: "" };
function formForStudent(student: Student): StudentForm { return { school_id: student.school_id, student_code: student.student_code, full_name: student.full_name, class_name: student.class_name, section: student.section ?? "", roll_number: student.roll_number?.toString() ?? "" }; }
function studentPayload(form: StudentForm) { return { school_id: form.school_id.trim(), student_code: form.student_code.trim(), full_name: form.full_name.trim(), class_name: form.class_name.trim(), section: form.section.trim() || null, roll_number: form.roll_number ? Number(form.roll_number) : null }; }

export default function StudentManagement({ adminName, initialError, initialStudents, stats, classCounts }: { adminName: string; initialError: string; initialStudents: Student[]; stats: Stats; classCounts: Record<string, number> }) {
  const router = useRouter(); const [supabase] = useState(createClient); const [students, setStudents] = useState(initialStudents); const [form, setForm] = useState<StudentForm>(emptyForm); const [editingStudent, setEditingStudent] = useState<Student | null>(null); const [search, setSearch] = useState(""); const [showForm, setShowForm] = useState(false); const [saving, setSaving] = useState(false); const [error, setError] = useState(initialError); const [message, setMessage] = useState("");
  const filteredStudents = useMemo(() => { const query = search.trim().toLowerCase(); if (!query) return students; return students.filter((student) => [student.school_id, student.full_name, student.student_code, student.class_name, student.section ?? ""].some((value) => value.toLowerCase().includes(query))); }, [search, students]);
  const totalClasses = useMemo(() => Object.keys(classCounts).length, [classCounts]);
  const topClasses = useMemo(() => Object.entries(classCounts).sort((a,b) => b[1]-a[1]).slice(0,5), [classCounts]);
  function updateForm(field: keyof StudentForm, value: string) { setForm((current) => ({ ...current, [field]: value })); } function resetNotices() { setError(""); setMessage(""); }
  async function refreshStudents() { const { data, error: queryError } = await supabase.from("students").select("id, school_id, student_code, full_name, class_name, section, roll_number").order("class_name").order("section").order("roll_number"); if (queryError) { setError(queryError.message); return; } setStudents((data ?? []) as Student[]); }
  async function saveStudent(event: FormEvent<HTMLFormElement>) { event.preventDefault(); resetNotices(); const payload = studentPayload(form); if (!payload.school_id || !payload.student_code || !payload.full_name || !payload.class_name) { setError("School ID, full name, student ID, and class are required."); return; } if (form.roll_number && (!Number.isInteger(Number(form.roll_number)) || Number(form.roll_number) < 0)) { setError("Roll number must be a non-negative whole number."); return; } setSaving(true); const { error: saveError } = editingStudent ? await supabase.from("students").update(payload).eq("id", editingStudent.id) : await supabase.from("students").insert(payload); setSaving(false); if (saveError) { setError(saveError.message); return; } await refreshStudents(); setMessage(editingStudent ? "Student record updated." : "Student added successfully."); setForm(emptyForm); setEditingStudent(null); setShowForm(false); }
  function beginEdit(student: Student) { resetNotices(); setEditingStudent(student); setForm(formForStudent(student)); setShowForm(true); } function closeForm() { setForm(emptyForm); setEditingStudent(null); setShowForm(false); }
  async function deleteStudent(student: Student) { if (!window.confirm(`Delete ${student.full_name}'s student record? This cannot be undone.`)) return; resetNotices(); const { error: deleteError } = await supabase.from("students").delete().eq("id", student.id); if (deleteError) { setError(deleteError.message); return; } await refreshStudents(); setMessage("Student record deleted."); }
  async function logout() { await supabase.auth.signOut(); router.replace("/login"); router.refresh(); }
  return <main className="dashboard"><nav className="nav admin-nav"><div><div className="brand">MINDVYORA</div><span className="pill">ADMIN</span></div><div className="nav-actions"><span className="muted">{adminName}</span><a className="button-secondary button-inline" href="/admin/resources">📚 Resources</a><a className="button-secondary button-inline" href="/admin/accounts">👥 Accounts</a><a className="button-secondary button-inline" href="/admin/messages">💬 Messages</a><a className="button-secondary button-inline" href="/admin/import">📥 Import Excel</a><button className="button-secondary button-inline" onClick={logout}>Logout</button></div></nav>
  <section className="admin-heading"><div><p className="eyebrow">ADMIN COMMAND CENTER</p><h1>Good to see you, {adminName.split(" ")[0]}.</h1><p className="muted">One place to see MINDVYORA activity and manage your students.</p></div><button className="button-inline" onClick={() => { resetNotices(); setForm(emptyForm); setEditingStudent(null); setShowForm(true); }}>+ Add Student</button></section>
  <section className="summary-grid admin-stats" aria-label="Admin overview"><div className="stat-card"><span className="muted">👨‍🎓 Students</span><strong>{students.length}</strong><small>registered learners</small></div><div className="stat-card"><span className="muted">🏫 Classes</span><strong>{totalClasses}</strong><small>active class groups</small></div><div className="stat-card"><span className="muted">📚 Resources</span><strong>{stats.resourceCount}</strong><small>published resources</small></div><div className="stat-card"><span className="muted">📢 Announcements</span><strong>{stats.announcementCount}</strong><small>posted announcements</small></div><div className="stat-card"><span className="muted">💬 Messages</span><strong>{stats.messageCount}</strong><small>message records</small></div></section>
  <section className="admin-command-grid"><article className="tile admin-panel"><div className="section-heading"><div><p className="eyebrow">QUICK ACTIONS</p><h2>Run MINDVYORA</h2></div></div><div className="quick-actions"><a href="/admin/resources" className="quick-action"><span>📚</span><div><strong>Manage Resources</strong><small>Upload files and target classes</small></div><b>→</b></a><a href="/admin/messages" className="quick-action"><span>💬</span><div><strong>Open Messages</strong><small>Reply to students who need you</small></div><b>→</b></a><a href="/admin/import" className="quick-action"><span>📥</span><div><strong>Import Students</strong><small>Bulk update from Excel</small></div><b>→</b></a><a href="/admin/accounts" className="quick-action"><span>👥</span><div><strong>Manage Accounts</strong><small>Create and maintain logins</small></div><b>→</b></a></div></article><article className="tile admin-panel"><div className="section-heading"><div><p className="eyebrow">CLASS PULSE</p><h2>Students by class</h2></div></div>{topClasses.length === 0 ? <p className="muted">No student classes yet.</p> : <div className="class-pulse">{topClasses.map(([name,count]) => <div className="class-row" key={name}><span>{name}</span><div><i style={{ width: `${Math.max(8, Math.round((count / Math.max(...Object.values(classCounts))) * 100))}%` }} /></div><strong>{count}</strong></div>)}</div>}</article></section>
  {error && <p className="error" role="alert">{error}</p>}{message && <p className="success" role="status">{message}</p>}
  {showForm && <section className="tile student-form-card"><div className="section-heading"><div><h2>{editingStudent ? "Edit Student" : "Add New Student"}</h2><p className="muted">Fields marked required must be completed.</p></div><button className="button-secondary button-inline" onClick={closeForm}>Cancel</button></div><form className="form student-form"><label>School ID<input value={form.school_id} onChange={(event) => updateForm("school_id", event.target.value)} required placeholder="e.g. SCHOOL001" /></label><label>Full Name<input value={form.full_name} onChange={(event) => updateForm("full_name", event.target.value)} required /></label><label>Student ID / Code<input value={form.student_code} onChange={(event) => updateForm("student_code", event.target.value)} required /></label><label>Class<input value={form.class_name} onChange={(event) => updateForm("class_name", event.target.value)} required /></label><label>Section<input value={form.section} onChange={(event) => updateForm("section", event.target.value)} /></label><label>Roll Number<input type="number" min="0" step="1" value={form.roll_number} onChange={(event) => updateForm("roll_number", event.target.value)} /></label><button disabled={saving}>{saving ? "Saving…" : editingStudent ? "Save Changes" : "Save Student"}</button></form></section>}
  <section className="student-list-section"><div className="section-heading"><div><p className="eyebrow">STUDENT DIRECTORY</p><h2>Students</h2><p className="muted">{filteredStudents.length} record{filteredStudents.length === 1 ? "" : "s"} shown</p></div><input className="student-search" aria-label="Search students" placeholder="Search name, ID, school ID, class, or section" value={search} onChange={(event) => setSearch(event.target.value)} /></div>{filteredStudents.length === 0 ? <div className="tile empty-state"><h3>No students found</h3><p className="muted">Try another search or add a student record.</p></div> : <div className="student-table-wrap"><table className="student-table"><thead><tr><th>Student</th><th>School ID</th><th>Student ID</th><th>Class</th><th>Section</th><th>Roll No.</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody>{filteredStudents.map((student) => <tr key={student.id}><td>{student.full_name}</td><td><span className="pill">{student.school_id}</span></td><td><span className="pill">{student.student_code}</span></td><td>{student.class_name}</td><td>{student.section ?? "—"}</td><td>{student.roll_number ?? "—"}</td><td className="table-actions"><button className="button-secondary button-inline" onClick={() => beginEdit(student)}>Edit</button><button className="button-danger button-inline" onClick={() => deleteStudent(student)}>Delete</button></td></tr>)}</tbody></table></div>}</section>
  <style jsx>{`.admin-stats{grid-template-columns:repeat(5,minmax(0,1fr))}.stat-card{position:relative;overflow:hidden}.stat-card small{display:block;margin-top:7px;color:#706b79;font-size:10px}.admin-command-grid{display:grid;grid-template-columns:1.1fr .9fr;gap:18px;margin:18px 0 30px}.admin-panel{padding:24px}.quick-actions{display:grid;gap:9px}.quick-action{display:flex;align-items:center;gap:12px;padding:13px;border:1px solid #302b38;border-radius:14px;background:rgba(255,255,255,.02);transition:.2s}.quick-action:hover{transform:translateX(4px);border-color:#594275;background:rgba(124,58,237,.06)}.quick-action>span{width:36px;height:36px;display:grid;place-items:center;border-radius:11px;background:#21182e}.quick-action div{flex:1}.quick-action strong,.quick-action small{display:block}.quick-action strong{font-size:12px}.quick-action small{margin-top:3px;color:#77717f;font-size:10px}.quick-action b{color:#a78bfa}.class-pulse{display:grid;gap:17px;margin-top:10px}.class-row{display:grid;grid-template-columns:70px 1fr 30px;gap:10px;align-items:center;font-size:11px}.class-row>div{height:7px;background:#211f27;border-radius:99px;overflow:hidden}.class-row i{display:block;height:100%;border-radius:99px;background:linear-gradient(90deg,#7c3aed,#22d3ee)}.class-row strong{text-align:right;color:#c9c3d1}@media(max-width:1000px){.admin-stats{grid-template-columns:repeat(3,1fr)}.admin-command-grid{grid-template-columns:1fr}}@media(max-width:650px){.admin-stats{grid-template-columns:repeat(2,1fr)}.class-row{grid-template-columns:58px 1fr 24px}}`}</style>
  </main>;
}
