"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { createClient } from "@/lib/supabase/client";

type Idea={id:string;title:string;category:string;problem:string|null;solution:string;status:string;coach_note:string|null;created_at:string;student_id:string};
const statuses=["new","reviewing","shortlisted","implemented","archived"];
const labels:Record<string,string>={new:"New",reviewing:"Reviewing",shortlisted:"Shortlisted",implemented:"Implemented",archived:"Archived"};
export default function AdminIdeas(){const [supabase]=useState(createClient);const [ideas,setIdeas]=useState<Idea[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [filter,setFilter]=useState("all");
 async function load(){setLoading(true);const {data,error}=await supabase.from("student_ideas").select("id,title,category,problem,solution,status,coach_note,created_at,student_id").order("created_at",{ascending:false});if(error)setError(error.message);setIdeas((data??[]) as Idea[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 async function setStatus(id:string,status:string){const {error}=await supabase.from("student_ideas").update({status,updated_at:new Date().toISOString()}).eq("id",id);if(error){setError(error.message);return}setIdeas(xs=>xs.map(x=>x.id===id?{...x,status}:x))}
 const shown=filter==="all"?ideas:ideas.filter(x=>x.status===filter);return <main className="dashboard admin-ideas"><nav className="nav admin-nav"><div><Link className="brand" href="/admin">MINDVYORA</Link><span className="pill">ADMIN</span></div><div className="nav-actions"><Link className="button-secondary button-inline" href="/admin">← Command Center</Link></div></nav><section className="admin-heading"><div><p className="eyebrow">INNOVATION INBOX</p><h1>Student Ideas 💡</h1><p className="muted">Review robotics, AI, electronics and innovation ideas shared by students.</p></div><span className="pill">{ideas.length} TOTAL</span></section><div className="idea-filters"><button className={filter==="all"?"active":""} onClick={()=>setFilter("all")}>All</button>{statuses.map(s=><button key={s} className={filter===s?"active":""} onClick={()=>setFilter(s)}>{labels[s]}</button>)}</div>{error&&<p className="error">{error}</p>}{loading?<div className="tile empty-state">Loading ideas…</div>:shown.length===0?<div className="tile empty-state"><h3>No ideas here yet.</h3><p className="muted">When students submit an idea, it will appear in this inbox.</p></div>:<section className="idea-admin-list">{shown.map(i=><article className="tile idea-admin-card" key={i.id}><div className="idea-admin-top"><div><span className="idea-category">{i.category}</span><h2>{i.title}</h2><small>{new Date(i.created_at).toLocaleString()}</small></div><select value={i.status} onChange={e=>setStatus(i.id,e.target.value)}>{statuses.map(s=><option key={s} value={s}>{labels[s]}</option>)}</select></div>{i.problem&&<div><strong>Problem observed</strong><p>{i.problem}</p></div>}<div><strong>Proposed solution</strong><p>{i.solution}</p></div></article>)}</section>}<style jsx global>{`.admin-ideas{max-width:1120px!important}.idea-filters{display:flex;gap:8px;flex-wrap:wrap;margin:18px 0}.idea-filters button{padding:8px 11px;border:1px solid #302b38;border-radius:999px;background:#111016;color:#96909d;font-size:9px}.idea-filters button.active{border-color:#7655a2;color:#d8c9ed;background:#21162e}.idea-admin-list{display:grid;gap:12px}.idea-admin-card{padding:23px}.idea-admin-top{display:flex;justify-content:space-between;gap:18px;align-items:flex-start;margin-bottom:18px}.idea-admin-card h2{margin:6px 0 3px;font-size:21px}.idea-admin-card small{color:#69646f;font-size:9px}.idea-admin-card strong{font-size:10px;color:#a8a1ae}.idea-admin-card p{color:#807a88;font-size:11px;line-height:1.65;margin:6px 0 16px}.idea-admin-card select{padding:9px 12px;border:1px solid #393240;border-radius:10px;background:#151219;color:#eee;font-size:10px}@media(max-width:650px){.idea-admin-top{flex-direction:column}.idea-admin-card select{width:100%}}`}</style></main>}
