"use client";
import { useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Announcement = { id: string; title: string; body: string; target_class: string | null; created_at: string };
type Resource = { id: string; title: string; description: string | null; file_name: string; file_path: string; mime_type: string | null; file_size: number | null; target_class: string | null; created_at: string };
function sizeLabel(bytes: number | null) { if (!bytes) return ""; const units = ["B", "KB", "MB", "GB"]; let n = bytes, i = 0; while (n >= 1024 && i < units.length - 1) { n /= 1024; i++; } return `${n < 10 && i > 0 ? n.toFixed(1) : Math.round(n)} ${units[i]}`; }
function icon(type: string | null) { if (type?.includes("pdf")) return "📕"; if (type?.includes("image")) return "🖼️"; if (type?.includes("presentation")) return "📊"; if (type?.includes("word")) return "📘"; if (type?.includes("sheet") || type?.includes("excel")) return "📗"; return "📎"; }
export default function StudentResources({ studentName, studentClass, announcements, resources }: { studentName: string; studentClass: string | null; announcements: Announcement[]; resources: Resource[] }) {
 const supabase = createClient(); const [error,setError]=useState(""); const [downloading,setDownloading]=useState<string | null>(null);
 async function download(r: Resource) { setError(""); setDownloading(r.id); const { data, error } = await supabase.storage.from("learning-resources").createSignedUrl(r.file_path, 60); if (error) setError(error.message); else window.open(data.signedUrl, "_blank", "noopener,noreferrer"); setDownloading(null); }
 return <main className="dashboard"><nav className="nav"><div><div className="brand">MINDVYORA</div><span className="pill">STUDENT · {studentClass ? `CLASS ${studentClass}` : "STUDENT"}</span></div><div className="nav-actions"><span className="muted">{studentName}</span><a className="button-secondary button-inline" href="/student">Dashboard</a><a className="button-secondary button-inline" href="/student/messages">Messages</a></div></nav><section className="admin-heading"><div><p className="eyebrow">LEARNING HUB</p><h1>Announcements & Resources</h1><p className="muted">{studentClass ? `Showing updates for Class ${studentClass} and anything shared with everyone.` : "Important notices and learning materials shared by your teacher."}</p></div></section>{error && <p className="error">{error}</p>}<section className="student-list-section"><h2>📣 Announcements</h2>{announcements.length===0?<div className="tile empty-state"><p className="muted">No announcements yet.</p></div>:<div className="grid" style={{marginTop:18}}>{announcements.map(a=><article className="tile lightning-card" key={a.id}><p className="eyebrow">{a.target_class ? `CLASS ${a.target_class}` : "ALL STUDENTS"} · {new Date(a.created_at).toLocaleString()}</p><h3>{a.title}</h3><p className="muted" style={{whiteSpace:"pre-wrap"}}>{a.body}</p></article>)}</div>}</section><section className="student-list-section"><h2>📚 Learning Files</h2>{resources.length===0?<div className="tile empty-state"><p className="muted">No files have been shared yet.</p></div>:<div className="grid" style={{marginTop:18}}>{resources.map(r=><article className="tile lightning-card" key={r.id}><div style={{fontSize:32}}>{icon(r.mime_type)}</div><p className="eyebrow">{r.target_class ? `CLASS ${r.target_class}` : "ALL STUDENTS"}</p><h3>{r.title}</h3><p className="muted">{r.description || r.file_name}</p><p className="muted">{sizeLabel(r.file_size)}</p><button className="button-inline" onClick={()=>download(r)} disabled={downloading===r.id}>{downloading===r.id?"Preparing…":"Download / Open"}</button></article>)}</div>}</section></main>;
}
