"use client";
import { FormEvent, useState } from "react";
import { createClient } from "@/lib/supabase/client";

type Announcement = { id: string; title: string; body: string; created_at: string };
type Resource = { id: string; title: string; description: string | null; file_name: string; file_path: string; mime_type: string | null; file_size: number | null; created_at: string };

function sizeLabel(bytes: number | null) { if (!bytes) return ""; const units = ["B", "KB", "MB", "GB"]; let n = bytes, i = 0; while (n >= 1024 && i < units.length - 1) { n /= 1024; i++; } return `${n < 10 && i > 0 ? n.toFixed(1) : Math.round(n)} ${units[i]}`; }

export default function AdminResources({ adminName, initialAnnouncements, initialResources }: { adminName: string; initialAnnouncements: Announcement[]; initialResources: Resource[] }) {
  const supabase = createClient();
  const [announcements, setAnnouncements] = useState(initialAnnouncements);
  const [resources, setResources] = useState(initialResources);
  const [title, setTitle] = useState(""); const [body, setBody] = useState(""); const [fileTitle, setFileTitle] = useState(""); const [description, setDescription] = useState(""); const [file, setFile] = useState<File | null>(null);
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  function clearNotices() { setError(""); setMessage(""); }
  async function announce(e: FormEvent) { e.preventDefault(); clearNotices(); if (!title.trim() || !body.trim()) return setError("Announcement title and message are required."); setBusy(true); const { data: { user } } = await supabase.auth.getUser(); if (!user) { setError("Session expired. Please sign in again."); setBusy(false); return; } const { data, error } = await supabase.from("announcements").insert({ title: title.trim(), body: body.trim(), created_by: user.id }).select("id,title,body,created_at").single(); if (error) setError(error.message); else { setAnnouncements([data, ...announcements]); setTitle(""); setBody(""); setMessage("Announcement published to students."); } setBusy(false); }
  async function upload(e: FormEvent) { e.preventDefault(); clearNotices(); if (!file) return setError("Choose a file first."); if (file.size > 25 * 1024 * 1024) return setError("File is too large. Maximum size is 25 MB."); const cleanTitle = (fileTitle.trim() || file.name.replace(/\.[^/.]+$/, "")).trim(); if (!cleanTitle) return setError("File title is required."); setBusy(true); const safeName = file.name.replace(/[^a-zA-Z0-9._-]/g, "_"); const path = `${Date.now()}-${crypto.randomUUID()}-${safeName}`; const { error: uploadError } = await supabase.storage.from("learning-resources").upload(path, file, { contentType: file.type || "application/octet-stream", upsert: false }); if (uploadError) { setError(uploadError.message); setBusy(false); return; } const { data, error: insertError } = await supabase.from("resources").insert({ title: cleanTitle, description: description.trim() || null, file_name: file.name, file_path: path, mime_type: file.type || null, file_size: file.size, created_by: (await supabase.auth.getUser()).data.user?.id }).select("id,title,description,file_name,file_path,mime_type,file_size,created_at").single(); if (insertError) { await supabase.storage.from("learning-resources").remove([path]); setError(insertError.message); } else { setResources([data, ...resources]); setFile(null); setFileTitle(""); setDescription(""); const input = document.getElementById("resource-file") as HTMLInputElement | null; if (input) input.value = ""; setMessage("Resource uploaded. Students can now download it."); } setBusy(false); }
  async function removeResource(resource: Resource) { if (!window.confirm(`Delete ${resource.file_name}?`)) return; clearNotices(); const { error: storageError } = await supabase.storage.from("learning-resources").remove([resource.file_path]); if (storageError) return setError(storageError.message); const { error } = await supabase.from("resources").delete().eq("id", resource.id); if (error) return setError(error.message); setResources(resources.filter((r) => r.id !== resource.id)); setMessage("Resource deleted."); }
  async function removeAnnouncement(id: string) { if (!window.confirm("Delete this announcement?")) return; const { error } = await supabase.from("announcements").delete().eq("id", id); if (error) return setError(error.message); setAnnouncements(announcements.filter((a) => a.id !== id)); }
  return <main className="dashboard"><nav className="nav admin-nav"><div><div className="brand">MINDVYORA</div><span className="pill">ADMIN</span></div><div className="nav-actions"><span className="muted">{adminName}</span><a className="button-secondary button-inline" href="/admin">Students</a><a className="button-secondary button-inline" href="/admin/messages">Messages</a><button className="button-secondary button-inline" onClick={async () => { await supabase.auth.signOut(); location.href = "/login"; }}>Logout</button></div></nav>
  <section className="admin-heading"><div><p className="eyebrow">COMMUNICATION</p><h1>Announcements & Resources</h1><p className="muted">Publish notices and share learning files with every student.</p></div></section>
  {error && <p className="error" role="alert">{error}</p>}{message && <p className="success" role="status">{message}</p>}
  <div className="grid" style={{ marginTop: 24 }}><section className="tile"><h2>📣 New Announcement</h2><form className="form" onSubmit={announce}><input placeholder="Announcement title" value={title} onChange={e => setTitle(e.target.value)} required /><textarea placeholder="Write your announcement…" value={body} onChange={e => setBody(e.target.value)} required rows={6} style={{ width: "100%", padding: 14, borderRadius: 12, border: "1px solid #3f3f46", background: "#18181b", color: "#fff", font: "inherit", resize: "vertical" }} /><button disabled={busy}>{busy ? "Publishing…" : "Publish Announcement"}</button></form></section>
  <section className="tile"><h2>📎 Upload Learning File</h2><p className="muted">PDF, Word, PowerPoint, Excel, images and other common files. Max 25 MB.</p><form className="form" onSubmit={upload}><input placeholder="File title" value={fileTitle} onChange={e => setFileTitle(e.target.value)} required /><input placeholder="Short description (optional)" value={description} onChange={e => setDescription(e.target.value)} /><input id="resource-file" type="file" onChange={e => setFile(e.target.files?.[0] ?? null)} required /><button disabled={busy}>{busy ? "Uploading…" : "Upload File"}</button></form></section></div>
  <section className="student-list-section"><div className="section-heading"><div><h2>Published Announcements</h2><p className="muted">Visible to authenticated students.</p></div></div>{announcements.length === 0 ? <div className="tile empty-state"><p className="muted">No announcements yet.</p></div> : <div className="grid" style={{ marginTop: 18 }}>{announcements.map(a => <article className="tile" key={a.id}><p className="eyebrow">{new Date(a.created_at).toLocaleString()}</p><h3>{a.title}</h3><p className="muted" style={{ whiteSpace: "pre-wrap" }}>{a.body}</p><button className="button-danger button-inline" onClick={() => removeAnnouncement(a.id)}>Delete</button></article>)}</div>}</section>
  <section className="student-list-section"><div className="section-heading"><div><h2>Learning Resources</h2><p className="muted">Students can view and download these files.</p></div></div>{resources.length === 0 ? <div className="tile empty-state"><p className="muted">No files uploaded yet.</p></div> : <div className="grid" style={{ marginTop: 18 }}>{resources.map(r => <article className="tile" key={r.id}><p className="eyebrow">{r.mime_type || "FILE"} · {sizeLabel(r.file_size)}</p><h3>{r.title}</h3><p className="muted">{r.description || r.file_name}</p><button className="button-danger button-inline" onClick={() => removeResource(r)}>Delete</button></article>)}</div>}</section>
  </main>;
}
